In [22]:
import pyqubo as pq
import numpy as np
import qubovert as qv

In [54]:
def get_Q(qubits, Dimension, A, b):
    QM = np.zeros((2*qubits*Dimension, 2*qubits*Dimension))
    for k in range(Dimension):
        for i in range(Dimension):
            for l in range(qubits):
                cef1 = pow(2,2*l)*pow(A[k][i],2)
                cef2 = pow(2,l+1)*A[k][i]*b[k]
                po1 = 4*i + l
                po2 = 4*i + l + 2
                QM[po1][po1] = QM[po1][po1] + cef1 - cef2
                QM[po2][po2] = QM[po2][po2] + cef1 + cef2
                
    for k in range(Dimension):
        for i in range(Dimension):
            for l1 in range(qubits-1):
                for l2 in range(l1+1,qubits):
                    qcef = pow(2, l1+l2+1)*pow(A[k][i],2)
                    po1 = 4*i + l1
                    po2 = 4*i + l2
                    QM[po1][po2] = QM[po1][po2] + qcef
                    po3 = 4*i + l1 + 2
                    po4 = 4*i + l2 + 2
                    QM[po3][po4] = QM[po3][po4] + qcef

    for k in range(Dimension):
        for i in range(Dimension-1):
            for j in range(i+1,Dimension):
                for l1 in range(qubits):
                    for l2 in range(qubits):
                        qcef = pow(2, l1+l2+1)*A[k][i]*A[k][j]
                        po1 = 4*i + l1
                        po2 = 4*j + l2
                        QM[po1][po2] = QM[po1][po2] + qcef
                        po3 = 4*i + l1 + 2
                        po4 = 4*j + l2 + 2
                        QM[po3][po4] = QM[po3][po4] + qcef
                        po5 = 4*i + l1
                        po6 = 4*j + l2 + 2
                        QM[po5][po6] = QM[po5][po6] - qcef
                        po7 = 4*i + l1 + 2
                        po8 = 4*j + l2
                        QM[po7][po8] = QM[po7][po8] - qcef
    return QM

In [56]:
A = np.array([[3, 1], [-1, 2]])
b = np.array([-1, 5])

get_ham(2,2, A, b)

qv.utils.matrix_to_qubo(Q)

{(0,): 89.0,
 (0, 1): 340.0,
 (0, 2): 680.0,
 (0, 4): 64.0,
 (0, 5): 128.0,
 (0, 6): 192.0,
 (0, 7): -128.0,
 (0, 8): -256.0,
 (1,): 348.0,
 (1, 2): 1360.0,
 (1, 4): 128.0,
 (1, 5): 256.0,
 (1, 6): 384.0,
 (1, 7): -256.0,
 (1, 8): -512.0,
 (2,): 1457.0,
 (2, 3): 340.0,
 (2, 4): 872.0,
 (2, 5): 384.0,
 (2, 6): 576.0,
 (2, 7): -384.0,
 (2, 8): -768.0,
 (3,): 332.0,
 (3, 4): 1232.0,
 (3, 5): -256.0,
 (3, 6): -384.0,
 (3, 7): 256.0,
 (3, 8): 512.0,
 (4,): 1115.0,
 (4, 5): -460.0,
 (4, 6): -664.0,
 (4, 7): 512.0,
 (4, 8): 1024.0,
 (5,): 80.0,
 (5, 6): 208.0,
 (6,): 263.0,
 (6, 7): 52.0,
 (6, 8): 104.0,
 (7,): 24.0,
 (7, 8): 208.0,
 (8,): 152.0}

In [52]:
help(qv.utils.QUBOMatrix)

Help on class QUBOMatrix in module qubovert.utils._qubomatrix:

class QUBOMatrix(qubovert.utils._pubomatrix.PUBOMatrix)
 |  QUBOMatrix(*args, **kwargs)
 |  
 |  QUBOMatrix.
 |  
 |  ``QUBOMatrix`` inherits some methods from ``PUBOMatrix``, see
 |  ``help(qubovert.utils.PUBOMattrix)``.
 |  
 |  A class to handle QUBO matrices. It is the same thing as a dictionary
 |  with some methods modified. Note that each key must be a tuple of two
 |  integers >= 0.
 |  
 |  One method is that values will always default to 0. Consider the following
 |  example:
 |  
 |  >>> d = QUBOMatrix()
 |  >>> print(d[(0,)]) # will print 0
 |  >>> d[(0,)] += 1
 |  >>> print(d) # will print {(0,): 1}
 |  
 |  Compared to an ordinary dictionary.
 |  
 |  >>> g = dict()
 |  >>> print(g[(0,)]) # will raise KeyError
 |  >>> g[(0,)] += 1 # will raise KeyError, since (0,) was never set
 |  
 |  One method of QUBOMatrix is that it will always keep the QUBO
 |  upper triangular! Consider the following example:
 |  
 | 

In [43]:
A = np.array([[2, -1], [3, 1]])
b = np.array([3,2])

Q = get_ham(2,2, A, b)

qubo = qv.utils.matrix_to_qubo(Q)
print(qubo.pretty_str())

qubo.solve_bruteforce()

res = qv.sim.anneal_qubo(qv.utils.matrix_to_qubo(Q), num_anneals=10)

print(res.best)

-11.0 x(0) + 52.0 x(0) x(1) + 2.0 x(0) x(4) + 4.0 x(0) x(5) - 2.0 x(0) x(6) - 4.0 x(0) x(7) + 4.0 x(1) + 4.0 x(1) x(4) + 8.0 x(1) x(5) - 4.0 x(1) x(6) - 8.0 x(1) x(7) + 37.0 x(2) + 52.0 x(2) x(3) - 2.0 x(2) x(4) - 4.0 x(2) x(5) + 2.0 x(2) x(6) + 4.0 x(2) x(7) + 100.0 x(3) - 4.0 x(3) x(4) - 8.0 x(3) x(5) + 4.0 x(3) x(6) + 8.0 x(3) x(7) + 4.0 x(4) + 8.0 x(4) x(5) + 12.0 x(5) + 8.0 x(6) x(7) + 4.0 x(7)
  state: {0: 1, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1, 7: 0}
  value: -13
   spin: False


In [48]:
A = np.array([[-7, -2], [6, 3]])
b = np.array([-4,-5])

Q = get_ham(3,2, A, b)
print(Q)
qubo = qv.utils.matrix_to_qubo(Q)
#print(qubo.pretty_str())

print(qubo.solve_bruteforce())

res = qv.sim.anneal_qubo(qv.utils.matrix_to_qubo(Q), num_anneals=10)

print(res.best)

[[  89.  340.  680.    0.   64.  128.  192. -128. -256.    0.    0.    0.]
 [   0.  348. 1360.    0.  128.  256.  384. -256. -512.    0.    0.    0.]
 [   0.    0. 1457.  340.  872.  384.  576. -384. -768.    0.    0.    0.]
 [   0.    0.    0.  332. 1232. -256. -384.  256.  512.    0.    0.    0.]
 [   0.    0.    0.    0. 1115. -460. -664.  512. 1024.    0.    0.    0.]
 [   0.    0.    0.    0.    0.   80.  208.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.  263.   52.  104.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.   24.  208.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.  152.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]]
{0: 0, 1: 1, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 1, 8: 1}
  state: {0: 0, 1: 1, 2: 0, 3: 0, 4: 0, 5: 0

In [36]:

from neal import SimulatedAnnealingSampler as SAS  # D-Wave's simluated annealing

res = SAS().sample_qubo(qubo, num_reads=1000)
dwave_F_solution = res.first.sample

print("dwave_F_solution :", dwave_F_solution)
print("Resulting F value:", res.first.energy + qubo_F.offset)


ValueError: not enough values to unpack (expected 2, got 1)